Разметка индексной страницы и каталога
htmlacademy-htmlcss/2087061-gllacy-34 pull request #2
Opened 2022-05-25 09:36 UTC by pppushinw

2022-05-28 04:21 UTC, Espanol-nikkol requested changes

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <a href="#" class="navigation-link">+7 800 555-86-28</a>
Ссылка для телефона должна быть ссылкой для телефона, а не просто так)

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <!-- /.navigation-link -->
С ними понятнее, где что находится, чем без них?

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <a href="#" class="navigation-link">Вход</a>
`кнопки <button>должны использоваться только для действий на странице.`

Вход, чаще всего, это все-таки открытие попапа с формой авторизации. Сейчас уже редко когда делают прям отдельную страничку для входа

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +        <ol class="slider-pagination">
Ol ли?) Нам имеет значение порядок просмотра фоток?

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <img src="" alt="Иконка мороженного">
Изображение контентное или декоративное?

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +          <input type="email" id="email"  name="email" placeholder="email@example.com">
Красота, ничего не забыл, работает - лайк

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +      <section class="delivery-form">
Section ли?
По логике, форма отправки в раздел отправки не входит разве?

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +          <p class="delivery-date">
p - это абзац текста
для обычного контейнера есть другой тег - div

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +          <p>Адрес главного офиса и офлайн-магазина:</p>
для коротких фраз есть span

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +          <b>+7 (812) 812-12-12</b>
а я вот хочу звонить по клику на телефон. Представляешь, какой требовательный пользователь, ужас просто. Что делать будем?)

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <label for="delivery-date-address">Дата</label>
не дата)

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <label for="delivery-date-phone">Телефон</label>
так дата или телефон? Выглядит как невнимательная копипаста)

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <a href="catalog.html" class="navigation-link">Каталог</a>
ссылочку бы на каталог, чтобы удобнее перемещаться между страничками сайта

2022-05-28 04:21 UTC, Espanol-nikkol commented on index.html
> +            <a href="#" class="navigation-link">2 товара</a>
Обрати внимание и на это тоже

2022-05-28 04:21 UTC, Espanol-nikkol commented on catalog.html
> +          <h1 class="visually-hidden">GllacyShop</h1>
Говорили об этом в конфе

2022-05-28 04:21 UTC, Espanol-nikkol commented on catalog.html
> +                    <a class="breadcrumbs-link">Каталог</a>
а это точно ссылка? Зачем нам ссылка на ту страницу, на которой мы находимся?

2022-05-28 04:21 UTC, Espanol-nikkol commented on catalog.html
> +              <a href="#" class="navigation-link navigation-link-active">Каталог</a>
аналогичный вопрос - должна ли быть здесь ссылка?

2022-05-28 04:21 UTC, Espanol-nikkol commented on catalog.html
> +
не хватает range элемента с ценой

2022-05-28 04:21 UTC, Espanol-nikkol commented on catalog.html
> +                            <b><img src="" alt="Добавить в корзину"></b>
Жирная картинка?) Или кнопка с декоративным изображением?

2022-05-28 04:21 UTC, Espanol-nikkol commented on catalog.html
> +            <button class="button">Показать еще</button>
Если это не кнопка отправки формы, то надо обязательно указывать type

2022-05-28 06:36 UTC, pppushinw commented on index.html
> +            <!-- /.navigation-link -->
)) с чем с ними?))

2022-05-28 06:41 UTC, pppushinw commented on index.html
> +            <img src="" alt="Иконка мороженного">
Я думаю все таки контентное

2022-06-06 13:24 UTC, Espanol-nikkol approved these changes

2022-06-06 13:24 UTC, merged